In [1]:
#1. Convert List to 1D Array
import numpy as np
a = [1, 2, 3, 4]
a = np.array(a)
print(a)

[1 2 3 4]


In [2]:
#2 Create 3x3 Matrix (2?10)
import numpy as np
a = np.arange(2, 11).reshape(3, 3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
#3. Null Vector (10) & Update Eighth Value
a = np.zeros(10)
a[7] = 4
print(a)

[0. 0. 0. 0. 0. 0. 0. 4. 0. 0.]


In [5]:
#4. Array from 10 to 25
array = np.arange(10, 26)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [6]:
#5 Conver array to float type
a = np.array([1, 2, 3, 4])
a = a.astype(float)
print(a)
print(a.dtype)

[1. 2. 3. 4.]
float64


In [7]:
#6 . Celsius to Fahrenheit Conversion
c = np.array([0, 12, 45.21, 34, 99.91])
f = (c * 9/5) + 32
print(f)

[ 32.     53.6   113.378  93.2   211.838]


In [8]:
#7. Append values to array
a = np.array([1, 2, 3])
a = np.append(a, [4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [9]:
#8. Array statistics functions
a = np.random.rand(10)
mean = np.mean(a)
median = np.median(a)
std = np.std(a)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std)

Mean: 0.5384332545400897
Median: 0.5881951359676294
Standard Deviation: 0.30483968688870366


In [10]:
#9. find min and max values
a = np.random.rand(10)
min_value = np.min(a)
max_value = np.max(a)
print("Min:", min_value)
print("Max:", max_value)

Min: 0.041923132639592686
Max: 0.6031683979008607


In [11]:
#10 Create a 3x3x3 array with random values.
a = np.random.rand(3, 3, 3)
print(a)
print(a.shape)

[[[0.99523286 0.55048982 0.0967488 ]
  [0.96882477 0.63115754 0.90378205]
  [0.87452237 0.86710741 0.59046932]]

 [[0.49108644 0.81318709 0.38582647]
  [0.13527062 0.48546702 0.3054617 ]
  [0.9967384  0.95065705 0.25067362]]

 [[0.03089019 0.92552258 0.19242197]
  [0.13970592 0.24272999 0.377694  ]
  [0.16386471 0.59859164 0.58678737]]]
(3, 3, 3)
